apiVersion: v1
kind: Service
metadata:
  name: {{ include "storefront.fullname" . }}-buyer
  labels:
    {{- include "storefront.labels" . | nindent 4 }}
    app.kubernetes.io/component: buyer
spec:
  type: ClusterIP
  selector:
    {{- include "storefront.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: buyer
  ports:
    - name: http
      port: {{ .Values.buyer.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storefront.fullname" . }}-seller
  labels:
    {{- include "storefront.labels" . | nindent 4 }}
    app.kubernetes.io/component: seller
spec:
  type: ClusterIP
  selector:
    {{- include "storefront.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: seller
  ports:
    - name: http
      port: {{ .Values.seller.port }}
      targetPort: http
      protocol: TCP