{{- range $agent := .Values.agents }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storefront.agentFullname" (dict "root" $ "agent" $agent) }}
  labels:
    {{- include "storefront.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $agent.component | default $agent.name | quote }}
spec:
  type: ClusterIP
  selector:
    {{- include "storefront.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $agent.component | default $agent.name | quote }}
  ports:
    - name: http
      port: {{ $agent.port }}
      targetPort: http
      protocol: TCP
---
{{- end }}
