"""VM listing schema helpers."""

from domains.vms.listings.buyer_cli import (
    format_accepted_escrows,
    format_demands,
    format_resource,
    short_ts,
    shorten,
)
from domains.vms.listings.models import (
    ComputeDomainResource,
    ComputeResource,
    ComputeResourcePortfolio,
    ERC20TokenMetadata,
    GPUModel,
    GpuInterconnect,
    Host,
    Listing,
    Region,
    TokenResource,
    OfferingMode,
)
from domains.vms.listings.host_csv_importer import (
    HostImportReport,
    HostImportRowResult,
    upsert_hosts_from_csv,
)
from domains.vms.listings.pricing import (
    extract_compute_from_order,
    extract_initial_price_from_order,
    resource_is_compute,
)
from domains.vms.listings.reconciler import (
    HELD_ALLOCATION_STATES,
    allocation_table_exists,
    available_compute_slices,
    closed_available_listing_ids,
    current_available_resource_keys,
    held_gpu_counts,
    held_gpu_counts_by_resource,
    ShapeFeasibility,
    declared_shape_feasibility,
    listing_pool_key,
    listing_resource_key,
    listing_shape_key,
    open_listing_resource_keys,
    stale_open_listing_ids,
)
from domains.vms.listings.listing_shapes import (
    SHAPE_SOURCE_OVERRIDE,
    ResolvedShape,
    ShapeResolution,
    resolve_shape,
    resolve_vm_listing_shapes,
)
from domains.vms.listings.resources import (
    ComputeGpuResourceAdapter,
    ResourceAdapter,
    TokenErc20ResourceAdapter,
    adapt_db_resource_to_domain_resource,
    adapt_domain_resource_to_db_resource,
    get_resource_adapter,
    get_supported_resource_types,
    parse_resource_from_dict,
    register_resource_adapter,
)
from domains.vms.listings.resource_csv_importer import (
    ImportReport,
    ImportRowResult,
    parse_accepted_escrows_cell,
    upsert_resources_from_csv,
    upsert_resources_from_csv_content,
)
from domains.vms.listings.strategy import (
    determine_strategy_from_order,
    determine_strategy_from_resources,
)

__all__ = [
    "SHAPE_SOURCE_OVERRIDE",
    "declared_shape_feasibility",
    "ResolvedShape",
    "ShapeFeasibility",
    "ShapeResolution",
    "resolve_shape",
    "resolve_vm_listing_shapes",
    "adapt_db_resource_to_domain_resource",
    "adapt_domain_resource_to_db_resource",
    "allocation_table_exists",
    "available_compute_slices",
    "ComputeDomainResource",
    "ComputeGpuResourceAdapter",
    "ComputeResource",
    "ComputeResourcePortfolio",
    "determine_strategy_from_order",
    "determine_strategy_from_resources",
    "ERC20TokenMetadata",
    "extract_compute_from_order",
    "extract_initial_price_from_order",
    "format_accepted_escrows",
    "format_demands",
    "format_resource",
    "GPUModel",
    "GpuInterconnect",
    "closed_available_listing_ids",
    "current_available_resource_keys",
    "get_resource_adapter",
    "get_supported_resource_types",
    "HELD_ALLOCATION_STATES",
    "held_gpu_counts",
    "held_gpu_counts_by_resource",
    "Host",
    "HostImportReport",
    "HostImportRowResult",
    "ImportReport",
    "ImportRowResult",
    "Listing",
    "listing_pool_key",
    "listing_resource_key",
    "listing_shape_key",
    "open_listing_resource_keys",
    "parse_resource_from_dict",
    "parse_accepted_escrows_cell",
    "Region",
    "register_resource_adapter",
    "ResourceAdapter",
    "resource_is_compute",
    "short_ts",
    "shorten",
    "stale_open_listing_ids",
    "TokenErc20ResourceAdapter",
    "TokenResource",
    "upsert_hosts_from_csv",
    "upsert_resources_from_csv",
    "upsert_resources_from_csv_content",
    "OfferingMode",
]
