"""Stateless client for the external Arkhai payments authority."""

from .reconciliation import (
    ReconciliationPass,
    reconcile_accepted_payments,
    run_payment_reconciliation,
)
from market_arkhai_payments.agreement import (
    PaymentSettlementData,
    agreement_from_bytes,
    agreement_payer_account,
    mandate_policy_for_agreement,
    selected_payment_option,
)
from market_arkhai_payments.buyer import ConfirmPayment, PaymentApproval
from market_arkhai_payments.client import PaymentsClient
from market_arkhai_payments.errors import (
    MandatePolicyError,
    PaymentApprovalDeclined,
    PaymentsAPIError,
    PaymentsBlocked,
    PaymentsError,
    PaymentsPollTimeout,
    PaymentsProtocolError,
    PaymentsTransportError,
    PaymentsUnavailable,
    ReceiptVerificationError,
)
from market_arkhai_payments.mandates import (
    MandatePolicy,
    PaymentsOptionParams,
    check,
    derive_mandate,
    duration_seconds,
    format_duration,
)
from market_arkhai_payments.models import (
    ApiError,
    ApprovalRequest,
    DealAttachment,
    Mandate,
    SignedReceipt,
    SignedTransactionSnapshot,
    StoredDealAttachment,
    StoredEvent,
)
from market_arkhai_payments.receipts import (
    agreement_hash,
    receipt_message,
    transaction_id,
    verify_receipt,
)
from market_arkhai_payments.seller import (
    ClientForOwner,
    NotPaid,
    NothingToReverse,
    PaymentSellerStage,
    ReceiptBlocked,
    ReceiptInvalid,
    ReceiptOutcome,
    ReceiptPending,
    ReceiptUnavailable,
    ReceiptVerified,
    RefundBlocked,
    RefundOutcome,
    RefundUnavailable,
    Refunded,
    servicing_stage,
)
from market_arkhai_payments.settlement_config import (
    ARKHAI_PAYMENTS_CONFIG_KEY,
    ARKHAI_PAYMENTS_MECHANISM,
    ArkhaiPaymentsConfig,
    ArkhaiPaymentsConfigurationError,
    ArkhaiPaymentsPublicationInput,
    create_arkhai_payments_registration,
    payments_client_for_owner,
)

__all__ = [
    "ARKHAI_PAYMENTS_CONFIG_KEY",
    "ARKHAI_PAYMENTS_MECHANISM",
    "ApiError",
    "ApprovalRequest",
    "ArkhaiPaymentsConfig",
    "ArkhaiPaymentsConfigurationError",
    "ArkhaiPaymentsPublicationInput",
    "ClientForOwner",
    "ConfirmPayment",
    "DealAttachment",
    "Mandate",
    "MandatePolicy",
    "MandatePolicyError",
    "NotPaid",
    "NothingToReverse",
    "PaymentApproval",
    "PaymentApprovalDeclined",
    "PaymentSellerStage",
    "PaymentSettlementData",
    "PaymentsAPIError",
    "PaymentsBlocked",
    "PaymentsClient",
    "PaymentsError",
    "PaymentsOptionParams",
    "PaymentsPollTimeout",
    "PaymentsProtocolError",
    "PaymentsTransportError",
    "PaymentsUnavailable",
    "ReceiptBlocked",
    "ReceiptInvalid",
    "ReceiptOutcome",
    "ReceiptPending",
    "ReceiptUnavailable",
    "ReceiptVerificationError",
    "ReceiptVerified",
    "ReconciliationPass",
    "RefundBlocked",
    "RefundOutcome",
    "RefundUnavailable",
    "Refunded",
    "SignedReceipt",
    "SignedTransactionSnapshot",
    "StoredDealAttachment",
    "StoredEvent",
    "agreement_from_bytes",
    "agreement_hash",
    "agreement_payer_account",
    "check",
    "create_arkhai_payments_registration",
    "derive_mandate",
    "duration_seconds",
    "format_duration",
    "mandate_policy_for_agreement",
    "payments_client_for_owner",
    "receipt_message",
    "reconcile_accepted_payments",
    "run_payment_reconciliation",
    "selected_payment_option",
    "servicing_stage",
    "transaction_id",
    "verify_receipt",
]
