# Generated from schema/payments.schema.json; do not edit.
# Upstream: arkhai-io/arkhai-payments@f16b1ebdca4e0977dae45bebe7b57cce9c1a08c2

# generated by datamodel-codegen:
#   filename:  payments.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ArkhaiPaymentsWireContract(RootModel[Any]):
    root: Annotated[Any, Field(title='arkhai-payments wire contract')]


class AccountId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Arkhai account UUID.',
            pattern='^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
        ),
    ]


class Amount(RootModel[str]):
    root: Annotated[str, Field(pattern='^[1-9][0-9]{0,37}$')]


class ApiErrorCode(Enum):
    invalid_request = 'invalid_request'
    authentication_required = 'authentication_required'
    caller_not_authorized = 'caller_not_authorized'
    account_not_found = 'account_not_found'
    transaction_not_found = 'transaction_not_found'
    part_not_found = 'part_not_found'
    mandate_expired = 'mandate_expired'
    fee_mismatch = 'fee_mismatch'
    dispute_authority_missing = 'dispute_authority_missing'
    deal_mismatch = 'deal_mismatch'
    attachment_not_found = 'attachment_not_found'
    invalid_event = 'invalid_event'
    request_id_reused = 'request_id_reused'
    hold_matured = 'hold_matured'
    hold_not_reversible = 'hold_not_reversible'
    insufficient_held_funds = 'insufficient_held_funds'
    insufficient_funds = 'insufficient_funds'
    account_directory_unavailable = 'account_directory_unavailable'
    ledger_unavailable = 'ledger_unavailable'
    internal_error = 'internal_error'


class Asset(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Z][A-Z0-9]{0,16}(\\/\\d{1,6})?$')]


class Authorities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: Annotated[list[AccountId], Field(max_length=16)]
    stop: Annotated[list[AccountId], Field(max_length=16)]
    reverse: Annotated[list[AccountId], Field(max_length=16)]


class BalanceAmount(RootModel[str]):
    root: Annotated[str, Field(pattern='^(0|[1-9][0-9]{0,37})$')]


class DealContent(RootModel[Any]):
    root: Any


class Duration(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: Annotated[
        str,
        Field(
            pattern='^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?=\\d)(\\d+H)?(\\d+M)?(\\d+S)?)?$'
        ),
    ]


class Fee(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bps: Annotated[int, Field(ge=0, le=10000)]


class Health(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['ok']


class HoldFor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    for_: Annotated[Duration, Field(alias='for')]


class HoldUntilStop(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    until: Literal['stop']


class Identity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scheme: Literal['ed25519']
    identifier: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$')]


class LifecycleKind(Enum):
    start = 'start'
    stop = 'stop'
    reverse = 'reverse'


class MinorUnits(RootModel[str]):
    root: Annotated[str, Field(pattern='^(0|[1-9][0-9]{0,37})$')]


class PartState(Enum):
    held = 'held'
    released = 'released'
    reversed = 'reversed'
    settled = 'settled'


class RequestId(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$')]


class Sha256Hex(RootModel[str]):
    root: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class SignatureProof(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scheme: Literal['ed25519']
    value: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{85}[AQgw]$')]


class StoredDealAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['deal']
    content: DealContent
    label: str | None = None
    sha256: Sha256Hex
    name: Literal['deal.json']
    mediaType: Literal['application/json']
    size: Annotated[
        int,
        Field(
            description='UTF-8 byte length of the JCS content.',
            ge=0,
            le=9007199254740991,
        ),
    ]
    uploader: AccountId


class TimedBalanceHold(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: Annotated[str, Field(min_length=1)]
    transaction: Sha256Hex
    part: Annotated[int, Field(ge=0, le=9007199254740991)]
    from_: Annotated[AccountId, Field(alias='from')]
    to: AccountId
    asset: Asset
    balance: BalanceAmount
    fee: Fee
    releaseAt: str


class UntilStopBalanceHold(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: Annotated[str, Field(min_length=1)]
    transaction: Sha256Hex
    part: Annotated[int, Field(ge=0, le=9007199254740991)]
    from_: Annotated[AccountId, Field(alias='from')]
    to: AccountId
    asset: Asset
    balance: BalanceAmount
    fee: Fee
    until: Literal['stop']


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: ApiErrorCode


class BalanceHold(RootModel[TimedBalanceHold | UntilStopBalanceHold]):
    root: TimedBalanceHold | UntilStopBalanceHold


class DealAttachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['deal']
    content: DealContent
    label: str | None = None


class DealCommitment(RootModel[Sha256Hex]):
    root: Sha256Hex


class EventCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: LifecycleKind
    part: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    amount: Amount | None = None
    payload: Annotated[
        Any | None, Field(description='Opaque JSON, recorded and never interpreted.')
    ] = None


class Hold(RootModel[HoldFor | HoldUntilStop]):
    root: Annotated[
        HoldFor | HoldUntilStop,
        Field(
            description="How long a part's money stays reversible and uncollectable by the payee."
        ),
    ]


class LifecycleEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: LifecycleKind
    part: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    amount: Amount | None = None
    payload: Annotated[
        Any | None, Field(description='Opaque JSON, recorded and never interpreted.')
    ] = None


class OncePart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['once']
    asset: Asset
    amount: Amount
    hold: Hold


class Part(RootModel[OncePart]):
    root: OncePart


class PartSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    part: Annotated[int, Field(ge=0, le=9007199254740991)]
    asset: Asset
    gross: Amount
    held: MinorUnits
    released: MinorUnits
    reversed: MinorUnits
    feePaid: MinorUnits
    hold: Hold
    releaseAt: Annotated[
        str | None,
        Field(description='UTC instant when a timed hold becomes releasable.'),
    ] = None
    status: PartState


class ReceiptPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    asset: Asset
    gross: Amount
    fee: Annotated[str, Field(pattern='^(0|[1-9][0-9]{0,37})$')]
    net: Annotated[str, Field(pattern='^(0|[1-9][0-9]{0,37})$')]
    hold: Hold


class StoredEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    account: AccountId
    requestId: RequestId
    event: LifecycleEvent
    receivedAt: Annotated[
        int,
        Field(
            description='Unix seconds when the service durably received the event.',
            ge=0,
            le=9007199254740991,
        ),
    ]


class Balance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    available: dict[Asset, BalanceAmount]
    held: list[BalanceHold]


class EventRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    account: AccountId
    requestId: RequestId
    event: LifecycleEvent


class Mandate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: Annotated[AccountId, Field(alias='from')]
    to: AccountId
    parts: Annotated[list[Part], Field(max_length=64, min_length=1)]
    deal: DealCommitment
    fee: Fee
    authorities: Authorities
    nonce: Annotated[str, Field(pattern='^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$')]
    expires: Annotated[
        int,
        Field(
            description='Unix seconds after which approval is refused.',
            ge=0,
            le=9007199254740991,
        ),
    ]


class Receipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transaction: Sha256Hex
    deal: DealCommitment
    from_: Annotated[AccountId, Field(alias='from')]
    to: AccountId
    ledger: Annotated[
        str, Field(description='Ledger transaction id for approval.', min_length=1)
    ]
    parts: Annotated[list[ReceiptPart], Field(min_length=1)]
    approvedAt: Annotated[
        int, Field(description='Unix seconds.', ge=0, le=9007199254740991)
    ]
    issuer: Identity


class SignedReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    receipt: Receipt
    proof: SignatureProof


class TransactionSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transaction: Sha256Hex
    receipt: SignedReceipt
    observedAt: Annotated[
        int,
        Field(
            description='Unix seconds at which this state was assembled.',
            ge=0,
            le=9007199254740991,
        ),
    ]
    parts: Annotated[list[PartSnapshot], Field(min_length=1)]
    events: list[StoredEvent]
    attachments: list[StoredDealAttachment]
    issuer: Identity


class ApprovalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mandate: Mandate
    attachments: list[DealAttachment] | None = None


class SignedTransactionSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    snapshot: TransactionSnapshot
    proof: SignatureProof
