apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-env.fullname" . }}
  labels:
    {{- include "test-env.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "test-env.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
