"""Bare-metal market domain schema."""

from .publication import (
    BARE_METAL_PUBLICATION_VIEW,
    available_bare_metal_listings,
    bare_metal_listing_key,
    trusted_bare_metal_projection,
)
from .projections import (
    BareMetalResourceProjection,
    TrustedBareMetalProjection,
)
from .provision_terms import (
    BARE_METAL_PROVISION_KIND,
    BARE_METAL_PROVISION_VERSION,
    BareMetalProvisionPayload,
    BareMetalProvisionTerms,
    make_bare_metal_provision_terms,
)
from .schema import (
    BARE_METAL_ACCESS_ACTIONS,
    BARE_METAL_EXECUTOR_KIND,
    BARE_METAL_SCHEMA_KIND,
    EXCLUSIVE_ALLOCATION_MODE,
    NODE_GRANT_ACCESS_ACTION,
    NODE_RECLAIM_ACCESS_ACTION,
    PHYSICAL_HOST_ID_REF_KEY,
    SSH_ACCESS_METHOD,
    BareMetalAccessResult,
    BareMetalLeaseCreate,
    BareMetalLeaseView,
    BareMetalListing,
    BareMetalMaterialization,
    BareMetalMessage,
    BareMetalReceipt,
    BareMetalTerms,
    bare_metal_executor_ref,
    materialization_to_lease_create,
    receipt_from_lease_view,
)
from .storefront_publication import (
    bare_metal_listing_candidates,
    close_stale_bare_metal_listings,
    closed_available_bare_metal_listing_ids,
    ensure_derived_bare_metal_listings_table,
    load_derived_bare_metal_listing,
    mark_derived_bare_metal_listings_closed,
    open_bare_metal_listing_keys,
    record_derived_bare_metal_listing,
    reopen_derived_bare_metal_listing_if_present,
    stale_open_bare_metal_listing_ids,
)

__all__ = [
    "BARE_METAL_ACCESS_ACTIONS",
    "BARE_METAL_EXECUTOR_KIND",
    "BARE_METAL_PROVISION_KIND",
    "BARE_METAL_PROVISION_VERSION",
    "BARE_METAL_PUBLICATION_VIEW",
    "BARE_METAL_SCHEMA_KIND",
    "EXCLUSIVE_ALLOCATION_MODE",
    "NODE_GRANT_ACCESS_ACTION",
    "NODE_RECLAIM_ACCESS_ACTION",
    "PHYSICAL_HOST_ID_REF_KEY",
    "SSH_ACCESS_METHOD",
    "BareMetalAccessResult",
    "BareMetalLeaseCreate",
    "BareMetalLeaseView",
    "BareMetalListing",
    "BareMetalMaterialization",
    "BareMetalMessage",
    "BareMetalProvisionPayload",
    "BareMetalProvisionTerms",
    "BareMetalReceipt",
    "BareMetalResourceProjection",
    "BareMetalTerms",
    "TrustedBareMetalProjection",
    "available_bare_metal_listings",
    "bare_metal_listing_key",
    "bare_metal_listing_candidates",
    "bare_metal_executor_ref",
    "close_stale_bare_metal_listings",
    "closed_available_bare_metal_listing_ids",
    "ensure_derived_bare_metal_listings_table",
    "load_derived_bare_metal_listing",
    "mark_derived_bare_metal_listings_closed",
    "make_bare_metal_provision_terms",
    "materialization_to_lease_create",
    "open_bare_metal_listing_keys",
    "record_derived_bare_metal_listing",
    "reopen_derived_bare_metal_listing_if_present",
    "receipt_from_lease_view",
    "stale_open_bare_metal_listing_ids",
    "trusted_bare_metal_projection",
]
