apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-env.fullname" . }}
  labels:
    {{- include "dev-env.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dev-env.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      port: {{ .Values.global.rpc.port }}
      targetPort: rpc
      protocol: TCP