services:
  agent:
    # image: us-east4-docker.pkg.dev/ww-migration-arkhai/a2a-agent/a2a-agent:v0.0.2
    image: test-agent
    # build: .
    platform: linux/amd64
    network_mode: host
    env_file:
      - ./agent/.env.c
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - zerotier-state:/var/lib/zerotier-one
      - ./agent/.env.c:/app/.env:rw

volumes:
  zerotier-state: