"""The compute provisioning family's wire contract.

Versioned contract models, the host, job, and system models, and the route
contracts the provisioning service authenticates and every typed client signs
from. A thin distribution: it carries no service code, so the family kit, the
service, its adapters, and its clients all depend on it without depending on
each other.
"""

from .contracts import (
    COMPUTE_PROVISIONING_CONTRACT_VERSION,
    CredentialEnvelope,
    FulfillmentAcceptanceResponse,
    FulfillmentRequestBody,
    FulfillmentScheduleRequest,
    FulfillmentScheduleResponse,
    FulfillmentStatusResponse,
    FulfillmentValidationResponse,
    LeaseForceRelease,
    LeaseListResponse,
    LeaseRegistration,
    LeaseReleaseOversight,
    LeaseRetryRelease,
    LeaseState,
    LeaseTermination,
    LeaseView,
    LifecycleEvent,
    ResultEnvelope,
    SUPPORTED_COMPUTE_PROVISIONING_MAJOR_VERSIONS,
    VersionedContractModel,
    contract_major,
    lease_state_for_reservation_state,
)
from .delivery import (
    ACCESS_DELIVERY_KIND,
    ACCESS_DELIVERY_SCHEMA_VERSION,
    AccessDelivery,
    AccessEndpoint,
    DELIVERY_EVIDENCE_RESULT_KIND,
    DeliveredCredential,
    DeliveryEvidence,
)
from .hosts import (
    ConnectionSubmission,
    ConnectionView,
    ConnectivityResult,
    HostCreate,
    HostListResponse,
    HostResponse,
    HostUpdate,
)
from .jobs import (
    JobCredentialsResponse,
    JobListResponse,
    JobListSort,
    JobLogsResponse,
    JobStatusResponse,
    JobSubmitResponse,
)
from .system import (
    ExecutionStatus,
    ExecutorStatus,
    HealthResponse,
    SystemStatusComponent,
    SystemStatusResponse,
    VersionResponse,
)
from .routes import (
    ADMIN_PROVISIONING_OPERATIONS,
    IDENTITY_IDENTIFIER_HEADER,
    IDENTITY_SCHEME_HEADER,
    PROVISIONING_ROLES,
    PROVISIONING_ROUTE_CONTRACTS,
    PROVISIONING_ROUTE_TABLE,
    ProvisioningRouteContract,
    ProvisioningRouteTable,
    REQUEST_ID_HEADER,
    ROLE_HEADER,
    SIGNATURE_HEADER,
    SIGNATURE_VERSION_HEADER,
    TIMESTAMP_HEADER,
    assemble_provisioning_route_table,
    canonical_provisioning_request_body,
    resolve_provisioning_route,
    resolve_provisioning_route_contract,
    route_contract_from_declaration,
)

__all__ = [
    "ACCESS_DELIVERY_KIND",
    "ACCESS_DELIVERY_SCHEMA_VERSION",
    "AccessDelivery",
    "AccessEndpoint",
    "DELIVERY_EVIDENCE_RESULT_KIND",
    "DeliveredCredential",
    "DeliveryEvidence",
    "COMPUTE_PROVISIONING_CONTRACT_VERSION",
    "CredentialEnvelope",
    "FulfillmentAcceptanceResponse",
    "FulfillmentRequestBody",
    "FulfillmentScheduleRequest",
    "FulfillmentScheduleResponse",
    "FulfillmentStatusResponse",
    "FulfillmentValidationResponse",
    "LeaseForceRelease",
    "LeaseListResponse",
    "LeaseRegistration",
    "LeaseReleaseOversight",
    "LeaseRetryRelease",
    "LeaseState",
    "LeaseTermination",
    "LeaseView",
    "LifecycleEvent",
    "ResultEnvelope",
    "SUPPORTED_COMPUTE_PROVISIONING_MAJOR_VERSIONS",
    "VersionedContractModel",
    "contract_major",
    "lease_state_for_reservation_state",
    "ConnectionSubmission",
    "ConnectionView",
    "ConnectivityResult",
    "HostCreate",
    "HostListResponse",
    "HostResponse",
    "HostUpdate",
    "JobCredentialsResponse",
    "JobListResponse",
    "JobListSort",
    "JobLogsResponse",
    "JobStatusResponse",
    "JobSubmitResponse",
    "ExecutionStatus",
    "ExecutorStatus",
    "HealthResponse",
    "SystemStatusComponent",
    "SystemStatusResponse",
    "VersionResponse",
    "ADMIN_PROVISIONING_OPERATIONS",
    "IDENTITY_IDENTIFIER_HEADER",
    "IDENTITY_SCHEME_HEADER",
    "PROVISIONING_ROLES",
    "PROVISIONING_ROUTE_CONTRACTS",
    "PROVISIONING_ROUTE_TABLE",
    "ProvisioningRouteContract",
    "ProvisioningRouteTable",
    "REQUEST_ID_HEADER",
    "ROLE_HEADER",
    "SIGNATURE_HEADER",
    "SIGNATURE_VERSION_HEADER",
    "TIMESTAMP_HEADER",
    "assemble_provisioning_route_table",
    "canonical_provisioning_request_body",
    "resolve_provisioning_route",
    "resolve_provisioning_route_contract",
    "route_contract_from_declaration",
]
