"""Negotiate controller — buyer ↔ seller negotiation protocol.

These buyer-facing protocol endpoints use the scheme-neutral marketplace v2
request contract. The signing requirement is documented in the OpenAPI
description; no FastAPI Security scheme applies.
"""

from __future__ import annotations

import logging
from typing import Any

from core_storefront.models.negotiation_models import (
    NegotiateContinueRequest,
    NegotiateContinueResponse,
    NegotiateNewRequest,
    NegotiateNewResponse,
)
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi_utils.cbv import cbv
from pydantic import ValidationError

import market_storefront.container as _container
from market_storefront.middleware import buyer_auth

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/negotiate", tags=["negotiate"])


def _proposal_payload(proposal: Any, settlement_selection: Any) -> Any:
    if proposal is not None:
        return proposal
    if settlement_selection is not None:
        return {"settlement_selection": settlement_selection.model_dump()}
    return None


@cbv(router)
class NegotiateController:
    def __init__(
        self,
        db=Depends(lambda: _container.resolved_sqlite_client),
    ) -> None:
        self._db = db

    @router.post(
        "/new",
        response_model=NegotiateNewResponse,
        summary="Start a new negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires marketplace v2 request "
            "authentication generated by the buyer CLI."
        ),
    )
    async def negotiate_new(
        self,
        body: NegotiateNewRequest,
        request: Request,
    ) -> NegotiateNewResponse:
        from market_storefront.utils.config import BASE_URL_OVERRIDE
        from market_storefront.utils.sync_negotiation import (
            OfferUnfulfillableError,
            StorefrontPausedError,
            start_sync_negotiation,
        )

        auth = await buyer_auth._verify(
            request,
            "negotiate_new",
            body.listing_id,
            body.buyer_principal,
            body.model_dump(mode="json"),
        )
        if auth.exact_retry:
            if auth.recorded_outcome is None:
                raise HTTPException(status_code=409, detail="request retry is pending")
            status_code, payload = auth.recorded_outcome
            if status_code >= 400:
                raise HTTPException(status_code=status_code, detail=payload)
            return NegotiateNewResponse.model_validate(payload)

        base_url = BASE_URL_OVERRIDE or ""
        signer = _container.resolved_marketplace_signer
        if signer is None:
            raise HTTPException(status_code=503, detail="storefront identity unavailable")
        try:
            result = await start_sync_negotiation(
                sqlite_client=self._db,
                our_listing_id=body.listing_id,
                buyer_principal=body.buyer_principal,
                seller_principal=signer.identity,
                provision_terms=body.provision_terms,
                proposal=_proposal_payload(
                    body.proposal,
                    body.settlement_selection,
                ),
                our_base_url=base_url,
                their_agent_url=body.buyer_agent_url,
            )
        except StorefrontPausedError as exc:
            raise HTTPException(
                status_code=503,
                detail={
                    "error": "paused",
                    "reason": exc.reason,
                    "hint": "Storefront or listing is paused; use admin API to advance or resume",
                },
            )
        except OfferUnfulfillableError as exc:
            raise HTTPException(
                status_code=409,
                detail={
                    "error": "offer_unfulfillable",
                    "reason": exc.reason,
                    "listing_id": exc.listing_id,
                    "hint": (
                        "Seller refused: listing is not in a state that can accept "
                        "new negotiations, or no matching compute is currently "
                        "available. Try a different listing."
                    ),
                },
            )
        except ValidationError as exc:
            raise HTTPException(
                status_code=400,
                detail={
                    "error": "incompatible_provision_terms",
                    "reason": str(exc),
                },
            )
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/new] %s", exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateNewResponse(**result)

    @router.post(
        "/{neg_id}",
        response_model=NegotiateContinueResponse,
        summary="Advance an existing negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires marketplace v2 request "
            "authentication."
        ),
    )
    async def negotiate_continue(
        self,
        neg_id: str,
        body: NegotiateContinueRequest,
        request: Request,
    ) -> NegotiateContinueResponse:
        from market_storefront.utils.sync_negotiation import continue_sync_negotiation

        auth = await buyer_auth._verify(
            request,
            "negotiate_continue",
            neg_id,
            body.buyer_principal,
            body.model_dump(mode="json"),
        )
        if auth.exact_retry:
            if auth.recorded_outcome is None:
                raise HTTPException(status_code=409, detail="request retry is pending")
            status_code, payload = auth.recorded_outcome
            if status_code >= 400:
                raise HTTPException(status_code=status_code, detail=payload)
            return NegotiateContinueResponse.model_validate(payload)

        if (
            body.action == "counter"
            and body.proposal is None
            and body.settlement_selection is None
        ):
            raise HTTPException(
                status_code=400,
                detail="'proposal' or 'settlement_selection' required for counter",
            )

        try:
            result = await continue_sync_negotiation(
                sqlite_client=self._db,
                neg_id=neg_id,
                buyer_action=body.action,
                buyer_proposal=_proposal_payload(
                    body.proposal,
                    body.settlement_selection,
                ),
                buyer_reason=body.reason,
                buyer_principal=body.buyer_principal,
                actor_principal=auth.principal,
            )
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/%s] %s", neg_id, exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateContinueResponse(**result)
