{{- if .Values.buyer.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agents.buyer.secretName" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  private_key: {{ .Values.buyer.secret.privKey | quote }}
  wallet_address: {{ .Values.buyer.secret.walletAddress | quote }}
  config-buyer-secret.yml: |
    buyer:
      private_key:    {{ .Values.buyer.secret.privKey | quote }}
      wallet_address: {{ .Values.buyer.secret.walletAddress | quote }}
{{- end }}
---
{{- if .Values.seller.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agents.seller.secretName" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  private_key: {{ .Values.seller.secret.privKey | quote }}
  wallet_address: {{ .Values.seller.secret.walletAddress | quote }}
  config-seller-secret.yml: |
    seller:
      private_key:    {{ .Values.seller.secret.privKey | quote }}
      wallet_address: {{ .Values.seller.secret.walletAddress | quote }}
{{- end }}
