{{- if .Values.buyer.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agents.buyer.secretName" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  privKey: {{ .Values.buyer.secret.privKey | quote }}
  walletAddress: {{ .Values.buyer.secret.walletAddress | quote }}
{{- end }}
---
{{- if .Values.seller.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agents.seller.secretName" . }}
  labels:
    {{- include "agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  privKey: {{ .Values.seller.secret.privKey | quote }}
  walletAddress: {{ .Values.seller.secret.walletAddress | quote }}
{{- end }}