"""Full API-tokens deal, driven by `market tokens buy`.

The domain's end-to-end (ARCHITECTURE.md, "API-tokens market domain"):

    discover → negotiate (new key) → settle → consume to 402
             → buy again into the existing key → consume succeeds

The topology (docker-compose.yml): a second registry speaking the
``api_tokens`` schema, the tokens service, the tokens storefront
(self-seeds one quota-backed listing pointing at the sample app), and
the sample app gated by the Python middleware. The buyer runs the same
`market` binary as the VM tests — its schema filter routes discovery to
the api-tokens registry while leaving the vms.compute registry alone.

Consuming runs against the gated sample app directly with the issued
bearer secret, exactly as a real client of that API would.
"""

from __future__ import annotations

import logging
import time
import tomllib

import httpx
import pytest

from src.settings import settings
from tests.e2e.roles.buyer_cli import BuyerCli, _alkahest_addresses_path

log = logging.getLogger(__name__)

pytestmark = pytest.mark.e2e_tokens_deal


@pytest.fixture(scope="module")
def tokens_buyer_cli(buyer_cli_binary, tmp_path_factory) -> BuyerCli:
    """A `market` CLI wired for the api-tokens deal.

    Differs from the VM ``buyer_cli`` fixture in two ways that matter:
    BOTH registries are configured (so the tokens plugin's schema filter
    is exercised — it must pick the api-tokens registry and skip the
    vms.compute one), and no explicit negotiation policy chain is pinned
    (so the tokens plugin uses its default ``listed_price`` terminal,
    which converges with the listed-price seller).
    """
    base = tmp_path_factory.mktemp("tokens_buyer_cli")
    home_dir = base / "home"
    state_dir = base / "state"
    config_dir = base / "config" / "arkhai"
    for d in (home_dir, state_dir, config_dir):
        d.mkdir(parents=True, exist_ok=True)

    private_key = str(settings.BUYER.PRIVATE_KEY or "")
    wallet_address = str(settings.BUYER.WALLET_ADDRESS or "")
    if not private_key or not wallet_address:
        pytest.skip("BUYER.PRIVATE_KEY / BUYER.WALLET_ADDRESS not configured")

    vms_registry = str(settings.REGISTRY.API_URL or "")
    tokens_registry = str(getattr(settings, "API_TOKENS", {}).get("REGISTRY_URL", "")
                          if hasattr(settings, "API_TOKENS") else "")
    if not tokens_registry:
        tokens_registry = str(settings.get("API_TOKENS.REGISTRY_URL", "") or "")
    if not tokens_registry:
        pytest.skip("API_TOKENS.REGISTRY_URL not configured")

    rpc_url = (
        str(settings.BUYER.CHAIN_RPC_URL or "").strip()
        or str(settings.RPC.URL or "").strip()
        or "ws://localhost:8545"
    )
    if rpc_url.startswith("http://"):
        rpc_url = "ws://" + rpc_url[len("http://"):]
    elif rpc_url.startswith("https://"):
        rpc_url = "wss://" + rpc_url[len("https://"):]

    alkahest_path = _alkahest_addresses_path()
    if not alkahest_path:
        pytest.skip("Could not locate alkahest_anvil_addresses.json")

    def q(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    registries = [r for r in (vms_registry, tokens_registry) if r]
    config_path = config_dir / "buyer.toml"
    config_path.write_text(
        "\n".join([
            "# Hermetic tokens-buyer config — generated by the e2e fixture.",
            "[wallet]",
            f"address     = {q(wallet_address)}",
            f"private_key = {q(private_key)}",
            "",
            "[chains.anvil]",
            f"rpc_url                      = {q(rpc_url)}",
            f"alkahest_address_config_path = {q(alkahest_path)}",
            "",
            "[registry]",
            "urls = [" + ", ".join(q(r) for r in registries) + "]",
            "",
            "# No [negotiation] policies: the tokens plugin uses its",
            "# default chain (answer_key_challenge + listed_price), which",
            "# pays the published per-token price and converges with the",
            "# listed-price seller.",
            "",
        ]),
        encoding="utf-8",
    )
    with config_path.open("rb") as f:
        tomllib.load(f)

    log.info("[tokens_buyer_cli] registries=%s rpc=%s", registries, rpc_url)
    yield BuyerCli(
        binary=buyer_cli_binary,
        config_path=config_path,
        state_dir=state_dir,
        home_dir=home_dir,
    )


def _forecast(secret: str, base_url: str) -> httpx.Response:
    with httpx.Client(timeout=15) as c:
        return c.get(
            f"{base_url.rstrip('/')}/api/forecast",
            headers={"Authorization": f"Bearer {secret}"},
        )


def test_tokens_full_deal(tokens_buyer_cli: BuyerCli) -> None:
    # --- 1. Buy 3 credits into a fresh key --------------------------------
    buy = tokens_buyer_cli.run([
        "tokens", "buy",
        "--quantity", "3",
        "--new-key",
        "--service-name", "weather-api",
        "--chain", "anvil",
        "--max-matches", "5",
        "--max-rounds", "10",
        "--poll-interval", "1.0",
        "--settlement-timeout", "300",
        "--expiration", "3600",
        "--yes",
    ], timeout=320.0)
    assert buy.returncode == 0, (
        f"`market tokens buy` (new key) failed rc={buy.returncode}\n"
        f"stdout:\n{buy.stdout()[-2000:]}\nstderr:\n{buy.stderr()[-2000:]}"
    )

    creds = buy.wait_for_event(
        "credentials_delivered", timeout=10.0,
    )["credentials"]
    secret = creds["secret"]
    base_url = creds["base_url"]
    key_id = creds["key_id"]
    assert secret and base_url and key_id, f"incomplete credentials: {creds}"
    log.info("[tokens] issued key %s, base_url %s", key_id, base_url)

    # --- 2. Consume the 3 credits, then hit 402 ---------------------------
    for i in range(3):
        r = _forecast(secret, base_url)
        assert r.status_code == 200, f"consume #{i+1} got {r.status_code}: {r.text}"
        assert r.json()["forecast"] == "sunny"

    drained = _forecast(secret, base_url)
    assert drained.status_code == 402, (
        f"expected 402 after draining, got {drained.status_code}: {drained.text}"
    )
    body = drained.json()
    assert body["error"] == "insufficient_credits"
    # The purchase pointer is the re-purchase loop's signpost.
    assert body["purchase"]["service_name"] == "weather-api"

    # --- 3. Top up the SAME key with 2 more credits -----------------------
    topup = tokens_buyer_cli.run([
        "tokens", "buy",
        "--quantity", "2",
        "--key-id", key_id,
        "--service-name", "weather-api",
        "--chain", "anvil",
        "--max-matches", "5",
        "--max-rounds", "10",
        "--poll-interval", "1.0",
        "--settlement-timeout", "300",
        "--expiration", "3600",
        "--yes",
    ], timeout=320.0)
    assert topup.returncode == 0, (
        f"`market tokens buy` (top-up) failed rc={topup.returncode}\n"
        f"stdout:\n{topup.stdout()[-2000:]}\nstderr:\n{topup.stderr()[-2000:]}"
    )
    topup.wait_for_event(
        "run_ended", predicate=lambda e: e.get("status") == "ready", timeout=10.0,
    )

    # --- 4. Consume succeeds again ----------------------------------------
    # The middleware's short verify cache hides the top-up briefly; poll
    # through that window (TTL is 3s in the sample app's compose env).
    deadline = time.monotonic() + 20.0
    last = None
    while time.monotonic() < deadline:
        r = _forecast(secret, base_url)
        if r.status_code == 200:
            assert r.json()["forecast"] == "sunny"
            break
        last = r
        time.sleep(1.0)
    else:
        raise AssertionError(
            "consume did not recover to 200 after top-up within 20s; "
            f"last={getattr(last, 'status_code', None)}: "
            f"{getattr(last, 'text', '')}"
        )
