"""Storefront FastAPI application.

Mirrors provisioning-service/src/main.py:

* ``FastAPI(lifespan=lifespan)`` — resolves singletons, starts background tasks.
* ``app.include_router()`` for every controller router.
* Admin auth via FastAPI Security() on individual routers — no middleware.
* X-Admin-Key OpenAPI security scheme registered so Swagger renders the
  Authorize button.

Global pause state
------------------
``_GLOBALLY_PAUSED`` is the module-level flag read by
``sync_negotiation.start_sync_negotiation``.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

import market_storefront.container as _container
from market_storefront.utils.config import CONFIG
from market_storefront.utils.sqlite_client import get_sqlite_client

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Global pause flag
# ---------------------------------------------------------------------------

_GLOBALLY_PAUSED: bool = False


def is_globally_paused() -> bool:
    return _GLOBALLY_PAUSED


def _set_globally_paused(value: bool) -> None:
    global _GLOBALLY_PAUSED
    _GLOBALLY_PAUSED = value


# ---------------------------------------------------------------------------
def run_serve(
    host: str = "0.0.0.0",
    port: int | None = None,
) -> None:
    """Launch uvicorn. Called by ``market-storefront serve``."""
    import uvicorn

    resolved_port = port if port is not None else CONFIG.port
    uvicorn.run(app, host=host, port=resolved_port, root_path=CONFIG.root_path)


# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(_: FastAPI):
    from market_storefront.agent import _startup_tasks
    from market_storefront.services import alkahest_service
    from market_storefront.services.listing_service import ListingService
    from market_storefront.services.negotiation_service import NegotiationService
    from market_storefront.services.policy_service import PolicyService
    from market_storefront.services.system_service import SystemService

    sqlite_client = get_sqlite_client()
    alkahest_client = alkahest_service.build_client(CONFIG)

    policy_svc = PolicyService(
        sqlite_client=sqlite_client,
        alkahest_client=alkahest_client,
        config=CONFIG,
        agent_id=CONFIG.agent_id,
    )
    listing_svc = ListingService(
        sqlite_client=sqlite_client,
        alkahest_client=alkahest_client,
        config=CONFIG,
    )
    negotiation_svc = NegotiationService(sqlite_client=sqlite_client)
    system_svc = SystemService(sqlite_client=sqlite_client, agent_id=CONFIG.agent_id)

    _container.resolved_sqlite_client = sqlite_client
    _container.resolved_alkahest_client = alkahest_client
    _container.resolved_alkahest_configured = alkahest_client is not None
    _container.resolved_policy_service = policy_svc
    _container.resolved_policy_pipeline_service = policy_svc  # backward compat
    _container.resolved_listing_service = listing_svc
    _container.resolved_negotiation_service = negotiation_svc
    _container.resolved_system_service = system_svc

    logger.info("[STARTUP] Singletons initialized")
    await _startup_tasks()
    logger.info("[STARTUP] Background tasks started")

    yield

    logger.info("[SHUTDOWN] Storefront shutting down")


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Arkhai Storefront",
    description=(
        "Seller-side storefront for the Arkhai compute marketplace.\n\n"
        "**Admin endpoints** require an `X-Admin-Key` header — use the "
        "🔒 Authorize button above to set it.\n\n"
        "**Buyer-facing endpoints** (`/api/v1/negotiate/*`, `/api/v1/settle/*`) "
        "require EIP-191 signed `X-Signature` + `X-Timestamp` headers; "
        "these are generated by the buyer CLI and are not standard OpenAPI auth schemes."
    ),
    version="1.0.0",
    lifespan=lifespan,
    root_path=CONFIG.root_path,
    swagger_ui_parameters={"persistAuthorization": True},
)


def _custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    schema.setdefault("components", {})
    schema["components"]["securitySchemes"] = {
        "AdminKey": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Admin-Key",
            "description": "Admin API key — required for all /api/v1/admin/* endpoints.",
        }
    }
    # Inject the gateway path prefix as the OpenAPI server URL so Swagger UI
    # generates correct curl examples. The FastAPI app root_path above drives
    # the docs page's OpenAPI URL; this servers block drives "try it out".
    root_path = CONFIG.root_path
    if root_path:
        schema["servers"] = [{"url": root_path}]
    app.openapi_schema = schema
    return schema


app.openapi = _custom_openapi

# Controller imports after module-level app exists.
from market_storefront.controllers.system_controller import router as system_router           # noqa: E402
from market_storefront.controllers.admin_controller import router as admin_router          # noqa: E402
from market_storefront.controllers.listings_controller import router as listings_router, admin_router as admin_listings_router       # noqa: E402
from market_storefront.controllers.negotiations_controller import router as negotiations_router  # noqa: E402
from market_storefront.controllers.negotiate_controller import router as negotiate_router     # noqa: E402
from market_storefront.controllers.settle_controller import router as settle_router, admin_settle_router           # noqa: E402
from market_storefront.controllers.alerts_controller import router as alerts_router           # noqa: E402
from market_storefront.controllers.identity_controller import router as identity_router       # noqa: E402

app.include_router(system_router)
app.include_router(admin_router)
app.include_router(listings_router)
app.include_router(admin_listings_router)
app.include_router(negotiations_router)
app.include_router(negotiate_router)
app.include_router(settle_router)
app.include_router(admin_settle_router)
app.include_router(alerts_router)
app.include_router(identity_router)

# ---------------------------------------------------------------------------
from fastapi import Request
from fastapi.responses import RedirectResponse


def _redirect_to(new_path: str):
    async def _handler(request: Request):
        # Preserve query string
        qs = request.url.query
        target = new_path + (f"?{qs}" if qs else "")
        return RedirectResponse(url=target, status_code=307)
    return _handler


# Admin routes
app.add_api_route("/admin/pause", _redirect_to("/api/v1/admin/pause"), methods=["POST"])
app.add_api_route("/admin/resume", _redirect_to("/api/v1/admin/resume"), methods=["POST"])
app.add_api_route("/admin/policy/seed", _redirect_to("/api/v1/admin/policy/seed"), methods=["POST"])
# Listing lifecycle (body-param style → path-param style handled by listings_controller)
app.add_api_route("/listings/create", _redirect_to("/api/v1/listings/create"), methods=["POST"])
app.add_api_route("/alerts/resource", _redirect_to("/api/v1/alerts/resource"), methods=["POST"])
app.add_api_route("/negotiate/new", _redirect_to("/api/v1/negotiate/new"), methods=["POST"])
