{{- $activeIdentity := .Values.global.provisioningIdentity -}}
{{- if or (ne .Values.identity.principal.scheme $activeIdentity.scheme) (ne .Values.identity.principal.identifier $activeIdentity.identifier) -}}
{{- fail "provisioning identity principal must match global.provisioningIdentity" -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provisioning.configMapName" . }}
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}
data:
  config-production.yml: |
    {{- $config := deepCopy .Values.config -}}
    {{- $_ := set $config "identity" .Values.identity.principal -}}
    {{- $_ := set $config "storefront_identity" (first .Values.storefrontIdentity.principals) -}}
    {{- $_ := set $config "admin_identity" (first .Values.adminIdentity.principals) -}}
    {{- if not $config.storefront_url -}}
      {{- $_ := set $config "storefront_url" (default (printf "http://%s-storefront-%s:%d" .Release.Name .Values.storefront.agentName (int .Values.storefront.port)) .Values.storefront.url) -}}
    {{- end -}}
    {{- $config | toYaml | nindent 4 }}
