{{- if .Values.sshKey.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioning.sshKeySecretName" . }}
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}
type: Opaque
stringData:
  id_ed25519: {{ .Values.sshKey.sshPrivateKey | quote }}
{{- end }}
---
{{- if .Values.sshDecryptionKey.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioning.sshDecryptionKeySecretName" . }}
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}
type: Opaque
stringData:
  config-provisioning-secrets.yml: |
    ssh_decryption_key: {{ .Values.sshDecryptionKey.key | quote }}
    inventory_ini: {{ .Values.inventory.hostsIni | quote }}
{{- end }}
