{{- if .Values.sshKey.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provisioning.sshKeySecretName" . }}
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}
type: Opaque
stringData:
  sshPrivateKey: {{ .Values.sshKey.sshPrivateKey | quote }}
{{- end }}