"""Shared VM-domain helpers used across buyer and storefront packages."""

from arkhai_vms.capability_shapes import (
    CapabilityShapeError,
    FlatShape,
    ShapeProblem,
    canonical_vm_shape,
    flatten_vm_shape,
    length_prefixed,
    length_prefixed_join,
    vm_shape_digest,
    vm_shape_problems,
)
from arkhai_vms.compute_requirements import (
    DIMENSION_KEYS,
    DISK_GB_DIMENSION,
    GPU_COUNT_DIMENSION,
    GPU_MODEL_ATTRIBUTE,
    RAM_GB_DIMENSION,
    VCPU_COUNT_DIMENSION,
    VM_CAPABILITY_SCHEMA,
)
from arkhai_vms.provision_terms import (
    VM_PROVISION_KIND,
    VmProvisionTerms,
    make_vm_provision_terms,
    normalize_vm_provision_terms,
    provision_compute_resource,
    provision_duration_seconds,
    provision_payload,
    provision_ssh_public_key,
    provision_start_utc,
)
from arkhai_vms.shape_generation import (
    DEFAULT_LISTING_SHAPE_GENERATOR,
    ListingShapeGenerator,
    gpu_count_shapes,
)
from arkhai_vms.schema import (
    VmListing,
    VmMaterialization,
    VmMessage,
    VmReceipt,
    VmResult,
    VmTerms,
)

__all__ = [
    "CapabilityShapeError",
    "FlatShape",
    "ShapeProblem",
    "canonical_vm_shape",
    "flatten_vm_shape",
    "length_prefixed",
    "length_prefixed_join",
    "vm_shape_digest",
    "vm_shape_problems",
    "DEFAULT_LISTING_SHAPE_GENERATOR",
    "DIMENSION_KEYS",
    "GPU_MODEL_ATTRIBUTE",
    "ListingShapeGenerator",
    "VM_CAPABILITY_SCHEMA",
    "gpu_count_shapes",
    "DISK_GB_DIMENSION",
    "GPU_COUNT_DIMENSION",
    "RAM_GB_DIMENSION",
    "VCPU_COUNT_DIMENSION",
    "VM_PROVISION_KIND",
    "VmListing",
    "VmMaterialization",
    "VmMessage",
    "VmProvisionTerms",
    "VmReceipt",
    "VmResult",
    "VmTerms",
    "make_vm_provision_terms",
    "normalize_vm_provision_terms",
    "provision_compute_resource",
    "provision_duration_seconds",
    "provision_payload",
    "provision_ssh_public_key",
    "provision_start_utc",
]
