"""Reusable FastAPI application composition for storefront executables.

Domain storefronts still own their routers, lifespan setup, and domain-specific
startup tasks. This module owns the generic FastAPI shell shared by storefront
executables: title/description/version/root path, Swagger settings, admin-key
OpenAPI installation, and router registration.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

from core_storefront.openapi import install_admin_key_openapi


@dataclass(frozen=True)
class StorefrontAppConfig:
    """Configuration for a storefront FastAPI app shell."""

    title: str
    description: str
    version: str = "1.0.0"
    root_path: str = ""
    swagger_ui_parameters: dict[str, Any] | None = None


DEFAULT_STOREFRONT_DESCRIPTION = (
    "Seller-side storefront for the Arkhai compute marketplace.\n\n"
    "**Admin endpoints** require an `X-Admin-Key` header — use the "
    "🔒 Authorize button above to set it.\n\n"
    "**Buyer-facing endpoints** (`/api/v1/negotiate/*`, `/api/v1/settle/*`) "
    "require EIP-191 signed `X-Signature` + `X-Timestamp` headers; "
    "these are generated by the buyer CLI and are not standard OpenAPI auth schemes."
)


def default_storefront_app_config(*, root_path: str = "") -> StorefrontAppConfig:
    """Return the default app shell config used by storefront executables."""

    return StorefrontAppConfig(
        title="Arkhai Storefront",
        description=DEFAULT_STOREFRONT_DESCRIPTION,
        version="1.0.0",
        root_path=root_path,
        swagger_ui_parameters={"persistAuthorization": True},
    )


def build_storefront_app(
    *,
    config: StorefrontAppConfig,
    lifespan: Any | None = None,
    routers: Iterable[Any] = (),
) -> Any:
    """Build a FastAPI storefront app and register routers.

    ``FastAPI`` remains an optional/lazy import for the core package: concrete
    storefront executables already depend on FastAPI, while lower-level core
    tests can import this module without importing FastAPI until they call the
    builder.
    """

    from fastapi import FastAPI

    app = FastAPI(
        title=config.title,
        description=config.description,
        version=config.version,
        lifespan=lifespan,
        root_path=config.root_path,
        swagger_ui_parameters=config.swagger_ui_parameters,
    )

    for router in routers:
        app.include_router(router)

    install_admin_key_openapi(app, root_path=config.root_path)
    return app
