#!/usr/bin/env python3
"""Verify hosted release inputs and atomically render a non-secret Compose env."""

from __future__ import annotations

import argparse
import importlib.util
import os
from pathlib import Path
from typing import Any

_VERIFIER_PATH = Path(__file__).with_name("verify-hosted-release.py")
_SPEC = importlib.util.spec_from_file_location("verify_hosted_release", _VERIFIER_PATH)
if _SPEC is None or _SPEC.loader is None:  # pragma: no cover
    raise RuntimeError(f"cannot load hosted release verifier from {_VERIFIER_PATH}")
_VERIFIER = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_VERIFIER)
_MARKETPLACE_VERIFIER_PATH = Path(__file__).with_name("verify-marketplace-release.py")
_MARKETPLACE_SPEC = importlib.util.spec_from_file_location(
    "verify_marketplace_release",
    _MARKETPLACE_VERIFIER_PATH,
)
if _MARKETPLACE_SPEC is None or _MARKETPLACE_SPEC.loader is None:  # pragma: no cover
    raise RuntimeError(
        f"cannot load marketplace release verifier from {_MARKETPLACE_VERIFIER_PATH}"
    )
_MARKETPLACE_VERIFIER = importlib.util.module_from_spec(_MARKETPLACE_SPEC)
_MARKETPLACE_SPEC.loader.exec_module(_MARKETPLACE_VERIFIER)



class ComposePreparationError(RuntimeError):
    """Raised before Compose can consume an untrusted hosted release."""


def _reject_mismatched_override(name: str, expected: str) -> None:
    supplied = os.environ.get(name)
    if supplied is not None and supplied != expected:
        raise ComposePreparationError(
            f"{name} does not match the verified hosted release"
        )
    if name != "HOSTED_SETTLEMENT_VERIFIED_IMAGE":
        return
    aliases = {
        "HOSTED_SETTLEMENT_IMAGE_REFERENCE": expected.split("@", 1)[0],
        "HOSTED_SETTLEMENT_IMAGE_DIGEST": expected.split("@", 1)[-1],
    }
    for alias, alias_expected in aliases.items():
        supplied_alias = os.environ.get(alias)
        if supplied_alias is not None and supplied_alias != alias_expected:
            raise ComposePreparationError(
                f"{alias} does not match the verified hosted release"
            )


def _required_file(path: Path | None, name: str) -> Path:
    if path is None:
        raise ComposePreparationError(f"missing required hosted input {name}")
    if not path.is_file():
        raise ComposePreparationError(f"missing required hosted input {name}: {path}")
    return path


def _image(reference: Any, digest: Any) -> str:
    return f"{reference}@{digest}"


def _render_env(values: dict[str, str]) -> str:
    forbidden = ("SECRET", "TOKEN", "CREDENTIAL", "PRIVATE_KEY", "WEBHOOK")
    for name, value in values.items():
        if any(word in name.upper() for word in forbidden):
            raise ComposePreparationError(
                f"generated Compose env cannot contain {name}"
            )
        if "\n" in value or "\r" in value:
            raise ComposePreparationError(
                f"generated Compose env value {name} is invalid"
            )
    lines = ["# Generated by scripts/prepare-hosted-compose.py; do not edit."]
    lines.extend(f"{name}={value}" for name, value in sorted(values.items()))
    return "\n".join(lines) + "\n"


#: The marketplace coordinates a locally built consumer has no released source
#: for. Rendered empty rather than omitted: the environment's reader requires
#: the exact key set, and a development run reads an empty value as "local".
#: The image is not among them -- Compose refuses to start a service without
#: one -- so a local environment names the image it actually runs.
_LOCAL_MARKETPLACE_COORDINATES = (
    "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_PROVENANCE_SHA256",
    "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_SCHEMA_SHA256",
    "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_WHEELHOUSE_SHA256",
    "HOSTED_MARKETPLACE_VERIFIED_MANIFEST_SHA256",
    "HOSTED_MARKETPLACE_VERIFIED_SOURCE_COMMIT",
    "HOSTED_MARKETPLACE_VERIFIED_WORKFLOW_REF",
    "HOSTED_MARKETPLACE_VERIFIED_WORKFLOW_RUN_ID",
)


#: The producer coordinates a locally built authority has no released source
#: for. Same treatment as the consumer half above, and for the same reason: the
#: environment's reader requires the exact key set, and a development run reads
#: an empty value as "local". The image, the release directory, and the manifest
#: digest are not among them -- Compose refuses to start a service without an
#: image, it mounts the release directory, and the authority reports the digest
#: back through its readiness check -- so a local environment names what it
#: actually runs.
_LOCAL_HOSTED_COORDINATES = (
    "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ADDRESS",
    "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ID",
    "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_SCHEME",
    "HOSTED_SETTLEMENT_VERIFIED_CLIENT_WHEEL_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_CONFORMANCE_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_MIGRATIONS_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_OPENAPI_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_PROVENANCE_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_SERVICE_WHEEL_SHA256",
    "HOSTED_SETTLEMENT_VERIFIED_SOURCE_COMMIT",
    "HOSTED_SETTLEMENT_VERIFIED_WORKFLOW_REF",
)


def _hosted_provenance(production: dict[str, Any], *, release_dir: str) -> dict[str, str]:
    """Who published this producer, and from what.

    Every value here comes from a signature or from a hash covered by one.
    None of it has a local counterpart, which is why the local path renders the
    whole group empty instead of filling it from the build.
    """

    artifact_sha256 = production["artifact_sha256"]
    return {
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ADDRESS": str(
            production["authority_address"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ID": str(production["authority_id"]),
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_SCHEME": str(
            production["authority_scheme"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_CLIENT_WHEEL_SHA256": "sha256:"
        + str(production["client_wheel_sha256"]),
        "HOSTED_SETTLEMENT_VERIFIED_CONFORMANCE_SHA256": str(
            artifact_sha256["conformance"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256": "sha256:"
        + str(production["manifest_sha256"]),
        "HOSTED_SETTLEMENT_VERIFIED_MIGRATIONS_SHA256": str(
            artifact_sha256["migrations"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_OPENAPI_SHA256": str(artifact_sha256["openapi"]),
        "HOSTED_SETTLEMENT_VERIFIED_PROVENANCE_SHA256": str(
            artifact_sha256["provenance"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_SERVICE_WHEEL_SHA256": "sha256:"
        + str(production["service_wheel_sha256"]),
        "HOSTED_SETTLEMENT_VERIFIED_SOURCE_COMMIT": str(production["source_commit"]),
        "HOSTED_SETTLEMENT_VERIFIED_WORKFLOW_REF": str(production["workflow_ref"]),
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_DIGEST": str(
            production["manifest_digest"]
        ),
        "HOSTED_SETTLEMENT_VERIFIED_RELEASE_DIR": release_dir,
        "HOSTED_SETTLEMENT_VERIFIED_REPOSITORY": str(production["repository"]),
    }


def _hosted_contract(
    *,
    release_version: Any,
    api_version: Any,
    schema_version: Any,
    funding_profiles: Any,
    capabilities: Any,
) -> dict[str, str]:
    """What the producer serves.

    A build answers all of this about itself, which is why a locally built
    producer can fill the group from the artifacts it generated rather than
    from a release that does not exist.
    """

    return {
        "HOSTED_SETTLEMENT_VERIFIED_API_VERSION": str(api_version),
        "HOSTED_SETTLEMENT_VERIFIED_CAPABILITIES": ",".join(
            str(value) for value in capabilities
        ),
        "HOSTED_SETTLEMENT_VERIFIED_FUNDING_PROFILES": ",".join(
            str(value) for value in funding_profiles
        ),
        "HOSTED_SETTLEMENT_VERIFIED_RELEASE_VERSION": str(release_version),
        "HOSTED_SETTLEMENT_VERIFIED_SCHEMA_VERSION": str(schema_version),
    }


def prepare_compose_env(
    *,
    trust_path: Path,
    manifest_path: Path,
    wheel_path: Path,
    marketplace_manifest_path: Path | None,
    marketplace_manifest_sha256: str,
    marketplace_commit: str,
    marketplace_workflow_ref: str,
    marketplace_workflow_run_id: str,
    marketplace_image_digest: str,
    output_path: Path,
    release_mode: str = "attested",
    local_marketplace_image: str = "",
) -> str:
    """Render the Compose environment the protected stack runs under.

    The producer half is verified identically in both modes -- a development
    run consumes the same signed hosted release. Only the marketplace half
    differs: an attested run binds a verified consumer release, and a local one
    records that it has none.
    """

    production: dict[str, Any] = _VERIFIER.verify_release(
        trust_path=_required_file(trust_path, "HOSTED_RELEASE_TRUST"),
        manifest_path=_required_file(manifest_path, "HOSTED_RELEASE_MANIFEST"),
        wheel_path=_required_file(wheel_path, "HOSTED_CLIENT_WHEEL"),
    )
    marketplace: dict[str, Any] | None = None
    if release_mode == "attested":
        marketplace = _MARKETPLACE_VERIFIER.verify_marketplace_release(
            manifest_path=_required_file(
                marketplace_manifest_path,
                "HOSTED_MARKETPLACE_RELEASE_MANIFEST",
            ),
            expected_manifest_sha256=marketplace_manifest_sha256,
            expected_commit=marketplace_commit,
            expected_workflow_ref=marketplace_workflow_ref,
            expected_workflow_run_id=marketplace_workflow_run_id,
            expected_image_digest=marketplace_image_digest,
        )
    verified_image = _image(
        production["service_image_reference"], production["service_image_digest"]
    )
    if marketplace is None:
        if not local_marketplace_image:
            raise ComposePreparationError(
                "a local environment must name the marketplace image it runs"
            )
        verified_marketplace_contract = {
            name: "" for name in _LOCAL_MARKETPLACE_COORDINATES
        }
        verified_marketplace_contract["HOSTED_MARKETPLACE_VERIFIED_REPOSITORY"] = (
            "arkhai-io/simple-compute-market"
        )
        verified_marketplace_contract["HOSTED_MARKETPLACE_VERIFIED_IMAGE"] = (
            local_marketplace_image
        )
    else:
        verified_marketplace_image = _image(
            marketplace["service_image_reference"],
            marketplace["service_image_digest"],
        )
        verified_marketplace_contract = {
            "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_PROVENANCE_SHA256": str(
                marketplace["artifacts"]["provenance"]["sha256"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_SCHEMA_SHA256": str(
                marketplace["artifacts"]["settlement_config_schema"]["sha256"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_ARTIFACT_WHEELHOUSE_SHA256": str(
                marketplace["artifacts"]["wheelhouse"]["sha256"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_IMAGE": verified_marketplace_image,
            "HOSTED_MARKETPLACE_VERIFIED_MANIFEST_SHA256": str(
                marketplace["manifest_sha256"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_REPOSITORY": str(marketplace["repository"]),
            "HOSTED_MARKETPLACE_VERIFIED_SOURCE_COMMIT": str(
                marketplace["source_commit"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_WORKFLOW_REF": str(
                marketplace["workflow_ref"]
            ),
            "HOSTED_MARKETPLACE_VERIFIED_WORKFLOW_RUN_ID": str(
                marketplace["workflow_run_id"]
            ),
        }
    verified_hosted_contract = {
        **_hosted_provenance(
            production, release_dir=str(manifest_path.resolve().parent)
        ),
        **_hosted_contract(
            release_version=production["release_version"],
            api_version=production["api_version"],
            schema_version=production["schema_version"],
            funding_profiles=production["funding_profiles"],
            capabilities=production["capabilities"],
        ),
        "HOSTED_SETTLEMENT_VERIFIED_IMAGE": verified_image,
    }
    for name, expected in {
        **verified_marketplace_contract,
        **verified_hosted_contract,
    }.items():
        _reject_mismatched_override(name, expected)
    content = _render_env(
        {**verified_marketplace_contract, **verified_hosted_contract}
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(output_path)
    return verified_image


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trust", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--wheel", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--marketplace-manifest", type=Path)
    parser.add_argument("--marketplace-manifest-sha256", default="")
    parser.add_argument("--marketplace-source-commit", default="")
    parser.add_argument("--marketplace-workflow-ref", default="")
    parser.add_argument("--marketplace-workflow-run-id", default="")
    parser.add_argument("--marketplace-image-digest", default="")
    parser.add_argument("--local-marketplace-image", default="")
    parser.add_argument(
        "--release-mode",
        choices=("attested", "local"),
        default="attested",
        help="attested verifies a released consumer; local renders the same "
        "environment for a development stack that has none.",
    )
    args = parser.parse_args()
    if args.release_mode == "attested" and args.marketplace_manifest is None:
        parser.error("--marketplace-manifest is required for an attested environment")
    try:
        image = prepare_compose_env(
            trust_path=args.trust,
            manifest_path=args.manifest,
            wheel_path=args.wheel,
            marketplace_manifest_path=args.marketplace_manifest,
            marketplace_manifest_sha256=args.marketplace_manifest_sha256,
            marketplace_commit=args.marketplace_source_commit,
            marketplace_workflow_ref=args.marketplace_workflow_ref,
            marketplace_workflow_run_id=args.marketplace_workflow_run_id,
            marketplace_image_digest=args.marketplace_image_digest,
            output_path=args.output,
            release_mode=args.release_mode,
            local_marketplace_image=args.local_marketplace_image,
        )
    except (
        _VERIFIER.ReleaseVerificationError,
        _MARKETPLACE_VERIFIER.MarketplaceReleaseVerificationError,
        ComposePreparationError,
    ) as exc:
        parser.error(str(exc))
    print(image)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
