#!/usr/bin/env python3
"""Verify hosted release inputs and atomically render a non-secret Compose env."""

from __future__ import annotations

import argparse
import importlib.util
import os
from pathlib import Path
from typing import Any

_VERIFIER_PATH = Path(__file__).with_name("verify-hosted-release.py")
_SPEC = importlib.util.spec_from_file_location("verify_hosted_release", _VERIFIER_PATH)
if _SPEC is None or _SPEC.loader is None:  # pragma: no cover
    raise RuntimeError(f"cannot load hosted release verifier from {_VERIFIER_PATH}")
_VERIFIER = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_VERIFIER)


class ComposePreparationError(RuntimeError):
    """Raised before Compose can consume an untrusted hosted release."""


def _reject_mismatched_override(name: str, expected: str) -> None:
    supplied = os.environ.get(name)
    if supplied is not None and supplied != expected:
        raise ComposePreparationError(f"{name} does not match the verified hosted release")
    if name != "HOSTED_SETTLEMENT_VERIFIED_IMAGE":
        return
    aliases = {
        "HOSTED_SETTLEMENT_IMAGE_REFERENCE": expected.split("@", 1)[0],
        "HOSTED_SETTLEMENT_IMAGE_DIGEST": expected.split("@", 1)[-1],
    }
    for alias, alias_expected in aliases.items():
        supplied_alias = os.environ.get(alias)
        if supplied_alias is not None and supplied_alias != alias_expected:
            raise ComposePreparationError(
                f"{alias} does not match the verified hosted release"
            )


def _required_file(path: Path | None, name: str) -> Path:
    if path is None:
        raise ComposePreparationError(f"missing required hosted input {name}")
    if not path.is_file():
        raise ComposePreparationError(f"missing required hosted input {name}: {path}")
    return path


def _required_text(value: str | None, name: str) -> str:
    if not value:
        raise ComposePreparationError(f"missing required hosted input {name}")
    return value


def _image(reference: Any, digest: Any) -> str:
    return f"{reference}@{digest}"


def _render_env(values: dict[str, str]) -> str:
    forbidden = ("SECRET", "TOKEN", "CREDENTIAL", "PRIVATE_KEY", "WEBHOOK")
    for name, value in values.items():
        if any(word in name.upper() for word in forbidden):
            raise ComposePreparationError(f"generated Compose env cannot contain {name}")
        if "\n" in value or "\r" in value:
            raise ComposePreparationError(f"generated Compose env value {name} is invalid")
    lines = ["# Generated by scripts/prepare-hosted-compose.py; do not edit."]
    lines.extend(f"{name}={value}" for name, value in sorted(values.items()))
    return "\n".join(lines) + "\n"


def prepare_compose_env(
    *,
    trust_path: Path,
    manifest_path: Path,
    wheel_path: Path,
    output_path: Path,
    mode: str = "production",
    service_wheel_path: Path | None = None,
    e2e_manifest_path: Path | None = None,
    e2e_manifest_sha256: str | None = None,
    e2e_fixture_wheel_path: Path | None = None,
    e2e_authority_id: str | None = None,
    e2e_authority_address: str | None = None,
    e2e_repository: str | None = None,
    e2e_workflow_ref: str | None = None,
    e2e_source_commit: str | None = None,
) -> str:
    if mode not in {"production", "hermetic"}:
        raise ComposePreparationError(f"unsupported hosted Compose mode {mode!r}")
    production: dict[str, Any] = _VERIFIER.verify_release(
        trust_path=_required_file(trust_path, "HOSTED_RELEASE_TRUST"),
        manifest_path=_required_file(manifest_path, "HOSTED_RELEASE_MANIFEST"),
        wheel_path=_required_file(wheel_path, "HOSTED_CLIENT_WHEEL"),
        service_wheel_path=(
            _required_file(service_wheel_path, "HOSTED_SERVICE_WHEEL")
            if mode == "hermetic"
            else service_wheel_path
        ),
    )
    verified_image = _image(
        production["service_image_reference"], production["service_image_digest"]
    )
    _reject_mismatched_override("HOSTED_SETTLEMENT_VERIFIED_IMAGE", verified_image)
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256",
        "sha256:" + str(production["manifest_sha256"]),
    )
    values = {
        "HOSTED_SETTLEMENT_VERIFIED_IMAGE": verified_image,
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256": (
            "sha256:" + str(production["manifest_sha256"])
        ),
    }
    selected_image = verified_image
    if mode == "hermetic":
        e2e = _VERIFIER.verify_hermetic_release(
            production=production,
            manifest_path=_required_file(
                e2e_manifest_path, "HOSTED_E2E_RELEASE_MANIFEST"
            ),
            manifest_sha256=_required_text(
                e2e_manifest_sha256, "HOSTED_E2E_MANIFEST_SHA256"
            ),
            fixture_wheel_path=_required_file(
                e2e_fixture_wheel_path, "HOSTED_E2E_FIXTURE_WHEEL"
            ),
            service_wheel_path=_required_file(
                service_wheel_path, "HOSTED_E2E_SERVICE_WHEEL"
            ),
            authority_id=_required_text(
                e2e_authority_id, "HOSTED_E2E_RELEASE_AUTHORITY_ID"
            ),
            authority_address=_required_text(
                e2e_authority_address, "HOSTED_E2E_RELEASE_AUTHORITY_ADDRESS"
            ),
            repository=_required_text(
                e2e_repository, "HOSTED_E2E_RELEASE_REPOSITORY"
            ),
            workflow_ref=_required_text(
                e2e_workflow_ref, "HOSTED_E2E_RELEASE_WORKFLOW_REF"
            ),
            source_commit=_required_text(
                e2e_source_commit, "HOSTED_E2E_RELEASE_SOURCE_COMMIT"
            ),
        )
        authority_image = _image(
            e2e["authority_image_reference"], e2e["authority_image_digest"]
        )
        simulator_image = _image(
            e2e["simulator_image_reference"], e2e["simulator_image_digest"]
        )
        values.update(
            {
                "HOSTED_SETTLEMENT_VERIFIED_IMAGE": authority_image,
                "HOSTED_E2E_VERIFIED_AUTHORITY_IMAGE": authority_image,
                "HOSTED_E2E_VERIFIED_SIMULATOR_IMAGE": simulator_image,
                "HOSTED_E2E_VERIFIED_MANIFEST_DIGEST": str(e2e["manifest_digest"]),
                "HOSTED_SETTLEMENT_MIGRATE_COMMAND": "hosted-settlement-e2e-migrate",
                "HOSTED_SETTLEMENT_API_COMMAND": "hosted-settlement-e2e-api",
                "HOSTED_SETTLEMENT_WORKER_COMMAND": "hosted-settlement-e2e-worker",
                "HOSTED_SETTLEMENT_WORKER_INTERVAL": "1",
                "HOSTED_E2E_FIXTURE_VERSION": str(e2e["fixture_version"]),
                "HOSTED_E2E_CONTROL_PROTOCOL": str(e2e["control_protocol"]),
                "HOSTED_E2E_SIMULATOR_SCHEMA_VERSION": str(
                    e2e["simulator_schema_version"]
                ),
                "VMS_BOB_STRIPE_STOREFRONT_CONFIG": str(
                    (
                        Path(__file__).resolve().parents[1]
                        / "e2e-tests"
                        / "config"
                        / "hosted-storefront.toml"
                    ).resolve()
                ),
            }
        )
        selected_image = authority_image
    content = _render_env(values)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(output_path)
    return selected_image


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("production", "hermetic"), default="production")
    parser.add_argument("--trust", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--wheel", type=Path, required=True)
    parser.add_argument("--service-wheel", type=Path)
    parser.add_argument("--e2e-manifest", type=Path)
    parser.add_argument("--e2e-manifest-sha256")
    parser.add_argument("--e2e-fixture-wheel", type=Path)
    parser.add_argument("--e2e-authority-id")
    parser.add_argument("--e2e-authority-address")
    parser.add_argument("--e2e-repository")
    parser.add_argument("--e2e-workflow-ref")
    parser.add_argument("--e2e-source-commit")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        image = prepare_compose_env(
            mode=args.mode,
            trust_path=args.trust,
            manifest_path=args.manifest,
            wheel_path=args.wheel,
            service_wheel_path=args.service_wheel,
            e2e_manifest_path=args.e2e_manifest,
            e2e_manifest_sha256=args.e2e_manifest_sha256,
            e2e_fixture_wheel_path=args.e2e_fixture_wheel,
            e2e_authority_id=args.e2e_authority_id,
            e2e_authority_address=args.e2e_authority_address,
            e2e_repository=args.e2e_repository,
            e2e_workflow_ref=args.e2e_workflow_ref,
            e2e_source_commit=args.e2e_source_commit,
            output_path=args.output,
        )
    except (_VERIFIER.ReleaseVerificationError, ComposePreparationError) as exc:
        parser.error(str(exc))
    print(image)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
