#!/usr/bin/env python3
"""Verify hosted release inputs and atomically render a non-secret Compose env."""

from __future__ import annotations

import argparse
import importlib.util
import os
from pathlib import Path
from typing import Any

_VERIFIER_PATH = Path(__file__).with_name("verify-hosted-release.py")
_SPEC = importlib.util.spec_from_file_location("verify_hosted_release", _VERIFIER_PATH)
if _SPEC is None or _SPEC.loader is None:  # pragma: no cover
    raise RuntimeError(f"cannot load hosted release verifier from {_VERIFIER_PATH}")
_VERIFIER = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_VERIFIER)


class ComposePreparationError(RuntimeError):
    """Raised before Compose can consume an untrusted hosted release."""


def _reject_mismatched_override(name: str, expected: str) -> None:
    supplied = os.environ.get(name)
    if supplied is not None and supplied != expected:
        raise ComposePreparationError(
            f"{name} does not match the verified hosted release"
        )
    if name != "HOSTED_SETTLEMENT_VERIFIED_IMAGE":
        return
    aliases = {
        "HOSTED_SETTLEMENT_IMAGE_REFERENCE": expected.split("@", 1)[0],
        "HOSTED_SETTLEMENT_IMAGE_DIGEST": expected.split("@", 1)[-1],
    }
    for alias, alias_expected in aliases.items():
        supplied_alias = os.environ.get(alias)
        if supplied_alias is not None and supplied_alias != alias_expected:
            raise ComposePreparationError(
                f"{alias} does not match the verified hosted release"
            )


def _required_file(path: Path | None, name: str) -> Path:
    if path is None:
        raise ComposePreparationError(f"missing required hosted input {name}")
    if not path.is_file():
        raise ComposePreparationError(f"missing required hosted input {name}: {path}")
    return path


def _image(reference: Any, digest: Any) -> str:
    return f"{reference}@{digest}"


def _render_env(values: dict[str, str]) -> str:
    forbidden = ("SECRET", "TOKEN", "CREDENTIAL", "PRIVATE_KEY", "WEBHOOK")
    for name, value in values.items():
        if any(word in name.upper() for word in forbidden):
            raise ComposePreparationError(
                f"generated Compose env cannot contain {name}"
            )
        if "\n" in value or "\r" in value:
            raise ComposePreparationError(
                f"generated Compose env value {name} is invalid"
            )
    lines = ["# Generated by scripts/prepare-hosted-compose.py; do not edit."]
    lines.extend(f"{name}={value}" for name, value in sorted(values.items()))
    return "\n".join(lines) + "\n"


def prepare_compose_env(
    *,
    trust_path: Path,
    manifest_path: Path,
    wheel_path: Path,
    output_path: Path,
) -> str:
    production: dict[str, Any] = _VERIFIER.verify_release(
        trust_path=_required_file(trust_path, "HOSTED_RELEASE_TRUST"),
        manifest_path=_required_file(manifest_path, "HOSTED_RELEASE_MANIFEST"),
        wheel_path=_required_file(wheel_path, "HOSTED_CLIENT_WHEEL"),
    )
    verified_image = _image(
        production["service_image_reference"], production["service_image_digest"]
    )
    verified_manifest_sha256 = "sha256:" + str(production["manifest_sha256"])
    verified_manifest_digest = str(production["manifest_digest"])
    verified_client_sha256 = "sha256:" + str(production["client_wheel_sha256"])
    verified_release_dir = str(manifest_path.resolve().parent)
    verified_source_commit = str(production["source_commit"])
    verified_repository = str(production["repository"])
    verified_workflow_ref = str(production["workflow_ref"])
    verified_authority_id = str(production["authority_id"])
    verified_authority_scheme = str(production["authority_scheme"])
    verified_authority_address = str(production["authority_address"])
    _reject_mismatched_override("HOSTED_SETTLEMENT_VERIFIED_IMAGE", verified_image)
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256",
        verified_manifest_sha256,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_DIGEST",
        verified_manifest_digest,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_CLIENT_WHEEL_SHA256",
        verified_client_sha256,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_RELEASE_DIR",
        verified_release_dir,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_SOURCE_COMMIT",
        verified_source_commit,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_REPOSITORY",
        verified_repository,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_WORKFLOW_REF",
        verified_workflow_ref,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ID",
        verified_authority_id,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_SCHEME",
        verified_authority_scheme,
    )
    _reject_mismatched_override(
        "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ADDRESS",
        verified_authority_address,
    )
    content = _render_env(
        {
            "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ADDRESS": verified_authority_address,
            "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_ID": verified_authority_id,
            "HOSTED_SETTLEMENT_VERIFIED_AUTHORITY_SCHEME": verified_authority_scheme,
            "HOSTED_SETTLEMENT_VERIFIED_CLIENT_WHEEL_SHA256": verified_client_sha256,
            "HOSTED_SETTLEMENT_VERIFIED_IMAGE": verified_image,
            "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_SHA256": verified_manifest_sha256,
            "HOSTED_SETTLEMENT_VERIFIED_MANIFEST_DIGEST": verified_manifest_digest,
            "HOSTED_SETTLEMENT_VERIFIED_RELEASE_DIR": verified_release_dir,
            "HOSTED_SETTLEMENT_VERIFIED_SOURCE_COMMIT": verified_source_commit,
            "HOSTED_SETTLEMENT_VERIFIED_REPOSITORY": verified_repository,
            "HOSTED_SETTLEMENT_VERIFIED_WORKFLOW_REF": verified_workflow_ref,
        }
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(output_path)
    return verified_image


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trust", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--wheel", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        image = prepare_compose_env(
            trust_path=args.trust,
            manifest_path=args.manifest,
            wheel_path=args.wheel,
            output_path=args.output,
        )
    except (_VERIFIER.ReleaseVerificationError, ComposePreparationError) as exc:
        parser.error(str(exc))
    print(image)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
