"""Compatibility re-exports for VM compute listing reconciliation."""

from domains.vms.listings.reconciler import (
    HELD_ALLOCATION_STATES,
    allocation_table_exists,
    available_compute_slices,
    closed_available_listing_ids,
    current_available_resource_keys,
    ensure_derived_compute_listings_table,
    held_gpu_counts,
    held_gpu_counts_by_resource,
    load_derived_listing_for_slice,
    listing_pool_key,
    listing_resource_key,
    mark_derived_listings_closed,
    mark_derived_listings_open,
    open_listing_resource_keys,
    record_derived_listing,
    reopen_local_derived_listing,
    stale_open_listing_ids,
)

__all__ = [
    "HELD_ALLOCATION_STATES",
    "allocation_table_exists",
    "available_compute_slices",
    "closed_available_listing_ids",
    "current_available_resource_keys",
    "ensure_derived_compute_listings_table",
    "held_gpu_counts",
    "held_gpu_counts_by_resource",
    "load_derived_listing_for_slice",
    "listing_pool_key",
    "listing_resource_key",
    "mark_derived_listings_closed",
    "mark_derived_listings_open",
    "open_listing_resource_keys",
    "record_derived_listing",
    "reopen_local_derived_listing",
    "stale_open_listing_ids",
]
