apiVersion: v2
name: arkhai-node-operator
description: Arkhai node operator cloud stack
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: test-env
    version: "0.1.0"
    repository: "file://charts/test-env"
    condition: test-env.enabled
  - name: registry
    version: "0.1.0"
    repository: "file://charts/registry"
    condition: registry.enabled
  - name: agents
    version: "0.1.0"
    repository: "file://charts/agents"
    condition: agents.enabled
  - name: provisioning
    version: "0.1.0"
    repository: "file://charts/provisioning"
    condition: provisioning.enabled