apiVersion: v2
name: arkhai-node-operator
description: Arkhai node operator cloud stack
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: dev-env
    version: "0.1.0"
    repository: "file://charts/dev-env"
    condition: dev-env.enabled
  - name: registry
    version: "0.1.0"
    repository: "file://charts/registry"
    condition: registry.enabled
  - name: storefront
    version: "0.1.0"
    repository: "file://charts/storefront"
    condition: storefront.enabled
  - name: provisioning
    version: "0.1.0"
    repository: "file://charts/provisioning"
    condition: provisioning.enabled
  - name: validate-contracts
    version: "0.1.0"
    repository: "file://charts/validate-contracts"
    condition: validate-contracts.enabled
  - name: e2e-tests
    version: "0.1.0"
    repository: "file://charts/e2e-tests"
    condition: e2e-tests.enabled