# Install torch etc. or use our docker image and clone this repo
# pip install -e . --no-build-isolation
# To rebuild the C env:
# python setup.py build_ext --inplace
# Training:
# python -m pufferlib.pufferl train puffer_market
# Sweeps:
# python -m pufferlib.pufferl sweep puffer_market --<neptune/wandb> --tag <sweep name>
# Note: this is all the same as the docs. No difference for your env w/ current 3.0
# C test:
# bash scripts/build_ocean.sh market <local/fast>
# ./market

[base]
package = ocean
env_name = puffer_market
policy_name = Policy
rnn_name = Recurrent

[env]
# This is the number of environment simulated per worker/core
num_envs = 1024

# All exposed environment variables
episode_length = 1000
max_job_duration = 100
energy_gen = 10
energy_storage = 100
max_nodes = 100
max_space_tb = 100
buy_price_randomization = 0.2
job_efficiency_randomization = 0.2
reward_scale = 0.0001
space_tb_price = 0.03
a100_node_price = 5.31
a100_node_energy_kw = 6.5
h100_node_price = 15.92
h100_node_energy_kw = 10.0
energy_demand_base = 1500.0
energy_price_base = 20.0
energy_price_sensitivity = 0.0001
energy_demand_threshold = 1400
a1 = -374
b1 = -387
a2 = -4.6
b2 = -17.1
a3 = 3.2
b3 = 18.9
 
[vec]
# This is the number of cores. Total envs = env.num_envs * vec.num_envs
num_envs = 4

[train]
# Best settings. vf_clip_coef is aggressively low but the rest are reasonable.
name = marketplace_seller_agent
project = marketplace
total_timesteps = 100_000_000
use_rnn = True
update_epochs = 1
bptt_horizon = 64
checkpoint_interval = 200
log_interval = 10
adam_beta1 = 0.9223446120784968
adam_beta2 = 0.9418904801775516
adam_eps = 4.1808405477736747e-11
clip_coef = 0.3330004439971794
ent_coef = 0.0028005893553093466
gae_lambda = 0.9817211156052661
gamma = 0.9947092311365654
learning_rate = 0.019070502993686896
max_grad_norm = 1.9130472971582053
minibatch_size = 8192
prio_alpha = 0.99
prio_beta0 = 0.7552965379192393
vf_clip_coef = 0.1
vf_coef = 3.292769981187723
vtrace_c_clip = 2.6939928387562437
vtrace_rho_clip = 0.6513603468577192

# Alternate settings if the above gets unstable
#total_timesteps = 100_000_000
#adam_beta1 = 0.9109764991734199
#adam_beta2 = 0.9985139194195674
#adam_eps = 2.487083956093364e-9
#clip_coef = 0.1674137340268662
#ent_coef = 0.001402322657505479
#gae_lambda = 0.99364902402328
#gamma = 0.9924188400188361
#learning_rate = 0.014061052765541085
#max_grad_norm = 0.2898020872357432
#minibatch_size = 16384
#prio_alpha = 0.9877184059538485
#prio_beta0 = 0.09999999999999998
#vf_clip_coef = 0.9671558938774713
#vf_coef = 1.0765600879902826
#vtrace_c_clip = 3.1287697179359437
#vtrace_rho_clip = 0.6256051857893086

