component: zerotier
schema_version: 1
fields:
  NETWORK_NAME:
    required: true
    default: "Arkhai Network"
    description: "ZeroTier network name."
  ZEROTIER_NETWORK:
    required: true
    default: null
    description: "ZeroTier network ID."
